[showrunner]
current-show = 1

[database]
path = "12AM.db"
# echo = false

[server]
# host = "0.0.0.0"
# port = 8000
# storage-secret = "showrunner"

[logging]
level = "DEBUG"

[paths]
# scripts = "./scripts"
# exports = "./exports"

[plugins]
# disabled = ["thecuelist"]

[plugins.theatremix]
database = "mix/12AM.tmix"
